
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/personal/Footer";
import Navbar from "@/components/personal/Navbar";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // প্রয়োজনমতো ওজন সিলেক্ট করো
  variable: "--font-poppins", // অপশনাল, css var হিসেবে চাইলে
});



export const metadata: Metadata = {
  title: "MineralCat PTE",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins.variable} antialiased bg-white`}>
        {/* header */}
        <Navbar />        

        <section className="min-h-dvh">
          {children}
        </section>

        {/* footer */}
        <footer className="flex items-center justify-center  mt-10">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
