import type { Metadata } from "next";
import {Poppins } from "next/font/google";
import "./globals.css";
import Logo from "@/components/personal/Logo";
import Link from "next/link";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // প্রয়োজনমতো ওজন সিলেক্ট করো
  variable: "--font-poppins", // অপশনাল, css var হিসেবে চাইলে
});

export const metadata: Metadata = {
  title: "MineralCat PTE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins.variable} antialiased`}>
        {/* header */}
        <header className="flex items-center justify-between h-[110px] p-4 border border-red-700 rounded-full mt-7 w-[80%] mx-auto">
          {/* logo */}
          <div>
            <Logo />
          </div>
          {/* menu */}
          <nav className="flex items-center gap-4">
            <Link href="/" className="text-[20px] font-semibold text-gray-900">
              Home
            </Link>
            <Link href="/" className="text-[20px] font-semibold text-gray-900">
              Practice
            </Link>
            <Link href="/" className="text-[20px] font-semibold text-gray-900">
              Mock Test
            </Link>
            <Link href="/" className="text-[20px] font-semibold text-gray-900">
              Pricing
            </Link>
            <Link href="/" className="text-[20px] font-semibold text-gray-900">
              FAQ
            </Link>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
