import { Poppins } from "next/font/google";
import "./globals.css";

import Footer from './../components/personal/Footer';
import Navbar from './../components/personal/Navbar';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "MineralCat PTE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can add the font link tag here if hydration issues occur */}
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        /> */}
        {/* Use SVG favicon */}
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </head>
      <body className={`antialiased bg-white ${poppins.className}`}>
        <Navbar />
        <section className="min-h-dvh">
          {children}
        </section>
        <footer className="flex items-center justify-center mt-10">
          <Footer />
        </footer>
      </body>
    </html>
  );
}